[View in Colaboratory](https://colab.research.google.com/github/princekiran/EliteExports/blob/master/practice_numpy.ipynb)

In [2]:
import numpy as np
from pprint import pprint as pp
np.__version__

#each element in ndarray is an object of data-type object
student = np.dtype([('name','S20'), ('age', 'b1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a['age'],a['marks'])

[ True  True] [50. 75.]


In [0]:
#To findout shape of the array
k = np.array([[1,2,3],[4,5,6]])
#ndarray.shape = This array attribute returns a tuple consisting of array 
#dimentions. It also used to resize the array.
k.shape = (3,2)
k
'''
'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)'''

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a = np.arange(24)
#ndim = This array attribute returns the number of array dimentions
print(a.ndim)
print(a.flags)
# .itemsize = this array attribute returns lenght of each element in array
# in bytes
print(a.itemsize)
#To reshape the array 
k = a.reshape(2,4,3)
# .flags = It returns C,F,O,W,A,U
k.flags

1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
8


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [0]:
#np.empty: It creates uninitialized array of specified shape and dtype
a = np.empty([2,2], dtype = int)
print(a)
#np.zeros will returns specified array with all filled with zeros
b = np.zeros([3,2],dtype=[('x','i4'),('y','i4')])
print(b)
#np.ones will returns specified array with all filled with zeros
c = np.ones([3,2],dtype=[('x','i4'),('y','i4')])
print(c)


[[1 1]
 [1 0]]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[[(1, 1) (1, 1)]
 [(1, 1) (1, 1)]
 [(1, 1) (1, 1)]]


In [0]:
#np.asarray: It is equal to np.array except it has few parameters
a = [1,2,3] # list
c = [(4,5,6),(7,8)] # tuple
b = np.asarray(a,dtype=bool)
print(b)

[ True  True  True]


In [0]:
#np.frombuffer: This functions interprets a buffer as one-dimensional array.
a = 'Hello kiran'
b = np.frombuffer(a,dtype='S1')
print(b)

AttributeError: ignored

In [0]:
#np.fromiter : This function builds an ndarray object from any iter object
a = range(10)
print(a)
b = iter(a)
print(b)
c = np.fromiter(b, dtype = int)
print(c)

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]


In [0]:
#np.arange : This function returns an ndarray object containing evenly
#spaced values within a given range

a = np.arange(0,9,3,dtype=float)
print(a)

[0. 3. 6.]


In [0]:
#np.linspace: It is same like arange but it returns even spaces

a = np.linspace(0,9,8,retstep=True)
print(a)

(array([0.        , 1.28571429, 2.57142857, 3.85714286, 5.14285714,
       6.42857143, 7.71428571, 9.        ]), 1.2857142857142858)


In [0]:
#np.logspace : This function returns ndarray object which contains numbers 
# that are evenly spaced on a log scale

a = np.logspace(1,10,num=10,base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [0]:
#slicing, (Basic, field access, advanced indexing)

a = np.arange(14)
b = slice(2,9,2)
print(a[b])


#example 1:

c = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(c[...,1])
print(c[1,...])
print(c[...,1:])

[2 4 6 8]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [0]:
#Advance indexing

a = np.array([[4,3],[5,6],[7,9]])

print(a)

print(a[[0,2],[1,1]])

[[4 3]
 [5 6]
 [7 9]]
[3 9]


In [0]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

pp(x)

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,1],[0,2]])
y = x[rows,cols]

pp(y)

z = x[1:4,1:3]
k = x[1:4,[0,2]]

pp(k)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
array([[ 0,  1],
       [ 9, 11]])
array([[ 3,  5],
       [ 6,  8],
       [ 9, 11]])


In [0]:
#Boolean Array Indexing

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])

pp(x)

pp(x[x>4])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
array([ 5,  6,  7,  8,  9, 10, 11])


In [0]:
''' ~ is a complement operator. and using iscomplex method will filter
complex numbers
In this example, NaN (Not a Number) elements are 
omitted by using ~ (complement operator).
'''
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
pp(a[~np.isnan(a)])

array([1., 2., 3., 4., 5.])


In [0]:
#Broadcasting
#broadcasting refers to the ability of NumPy to treat arrays of different
#shapes during arithmetic operations.

#For same size arrays is very easy to do arithmetic operations
#But for different size of arrays we need to 
a = np.array([[1,2,4],[5,2,5]])
b = np.array([[4,5,6],[1,8,34]])

c = a*b

pp(c)

array([[  4,  10,  24],
       [  5,  16, 170]])


In [7]:
#Numpy learning once again. 

import numpy as np
np.__version__

a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
a = a.reshape(3,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
a.shape
a.size
a.itemsize

8

In [12]:
a = np.array([2,3,4])
type(a)

numpy.ndarray